import 'package:hive/hive.dart';

part 'UserPreferences.g.dart'; // This will be auto-generated by Hive

@HiveType(typeId: 1) // Use a unique type ID
class UserPreferences {
  @HiveField(0)
  final bool isDarkMode;

  @HiveField(1)
  final String sortOrder;

  UserPreferences({required this.isDarkMode, required this.sortOrder});
}
